### ISSUE TITLE
Docker image fails to run, when git command used in lita.gemspec

### ISSUE THREAD

**Issue by akotian** [litaio/docker-lita#1]
`lita.gemspec` has this line `spec.files  = `git ls-files`.split($/)`. However, when I tried to run this from docker image [litaio/lita](https://hub.docker.com/r/litaio/lita/) it failed with the following error.

```
There was an error parsing `Gemfile`: There was a Errno::ENOENT while load
Oct 26 01:11:42 lita-test.c.lita-test.internal docker[1643]: No such file or directory - git from
Oct 26 01:11:42 lita-test.c.lita-test.internal docker[1643]: /app/lita.gemspec:16:in ``'
Oct 26 01:11:42 lita-test.c.lita-test.internal docker[1643]: . Bundler cannot continue.
```

My guess is because the corresponding docker image does not have git installed. Also as a work around I was able to substitute the problematic line with `Dir.glob("{bin,lib}/**/*") + %w(LICENSE README.md)` and that worked well for me.

Thanks!

**Comment by jimmycuadra** [comment]
Hi! This image is intended for running an instance of Lita, which doesn't require evaluating any gemspec files. The gemspec is only necessary when building/publishing a gem. For this image, you just need a Gemfile, which is used with the `bundle` command from Bundler to install gems that have already been packaged and published to rubygems.org. For working on the Lita code itself, or for developing a plugin, take a look at the [development environment](https://github.com/litaio/development-environment). Hope that helps clear up the confusion.
